version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/server/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/daemon/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
