app = "periodo-translator-dev"
primary_region = "iad"

[build]

[env]
  HOSTNAME = "periodo-translator-dev.flycast"
  IDLE_TIMEOUT = "300"
  OUTPUT_DIR = "/out"
  ERROR_DIR = "/err"
  TO_CSV_DIR = "/to_csv"
  TO_TTL_DIR = "/to_ttl"

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
